version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli  # Ensure AWS CLI is available
  pre_build:
    commands:
      - echo "Preparing to package Lambda function..."
  build:
    commands:
      # Create a deployment package (ZIP file) for Lambda
      - echo "Zipping Lambda function code..."
      - zip -r function.zip testing-code-pipeline.py
      # Push the ZIP file to S3
      - echo "Uploading Lambda code to S3..."
      - aws s3 cp function.zip s3://cloud-hws3-lambda-for-codepipeline/
  post_build:
    commands:
      # Update the Lambda function using the S3 object
      - echo "Updating Lambda function with new code from S3..."
      - aws lambda update-function-code --function-name testing-code-pipeline --s3-bucket cloud-hws3-lambda-for-codepipeline --s3-key function.zip
      - echo "Lambda function updated successfully!"

artifacts:
  files:
    - function.zip  # Optionally save the ZIP file as a build artifact
